image: python:3.9

ports:
  - port: 8000
    onOpen: open-preview
  - port: 5000
    onOpen: open-preview

tasks:
  - name: Dependencies
    init: |
      pip install -r ./requirements.txt
      pip install .
    # set VS_CODE_REMOTE to False when working in gitpod's in-browser IDE
    # set to True when working in VS code remote desktop
    command: export TOXENV=py39 VS_CODE_REMOTE=False

vscode:
  extensions:
    - ms-python.python
