site_name: Hemlock
docs_dir: docs_md
site_dir: docs
repo_url: https://github.com/dsbowen/hemlock
edit_uri: edit/master/docs_md
nav:
  - Home: index.md
  - Tutorial:
    - Introduction: tutorial/intro.md
    - Your first project: tutorial/first_project.md
    - Running hemlock locally: tutorial/run_local.md
    - Question polymorphs: tutorial/qpolymorphs.md
    - Data: tutorial/data.md
    - Validate: tutorial/validate.md
    - Submit: tutorial/submit.md
    - Compile: tutorial/compile.md
    - Navigate: tutorial/navigate.md
    - Page logic: tutorial/page_logic.md
    - Comprehension check: tutorial/comp_check.md
    - Random assignment: tutorial/random_ass.md
    - Proposer branch: tutorial/proposer_branch.md
    - Responder branch: tutorial/responder_branch.md
    - Debugging: tutorial/debug.md
    - Deployment: tutorial/deploy.md
    - Bells and whistles: tutorial/extra.md
  - Setup:
    - Windows: setup/win.md
    - Windows Subsystem for Linux: setup/wsl.md
    - Mac: setup/mac.md
    - Linux: setup/linux.md
  - Application: 
    - Setting and initialization: app.md
    - Debugging: debug.md
  - Functions:
    - Compile: compile_functions.md
    - Debug: debug_functions.md
    - Submit: submit_functions.md
    - Validate: validate_functions.md
  - Models:
    - Bases: bases.md
    - Branch: branch.md
    - Choice: choice.md
    - Embedded data and timers: embedded.md
    - Function models: functions.md
    - Page: page.md
    - Participant: participant.md
    - Question: question.md
    - Workers: workers.md
  - Question polymorphs:
    - Check: check.md
    - Download: download.md
    - File upload: file.md
    - Input: input.md
    - Input group: input_group.md
    - Label: label.md
    - Range: range.md
    - Select: select.md
    - Textarea: textarea.md
  - Tools:
    - Comprehension check: comprehension.md
    - Language: lang.md
    - Navbar: navbar.md
    - Randomization: random.md
    - Statics: statics.md
    - Utilities: utils.md
  - Security: security.md
theme: readthedocs
extra_css:
  - css/extra.css