site_name: Hemlock
docs_dir: docs_md
site_dir: docs
repo_url: https://github.com/dsbowen/hemlock
edit_uri: edit/master/docs_md
nav:
  - Home: index.md
  - Contact: contact.md
  - Checklist: checklist.md
  - Tutorial:
    - Introduction: tutorial/intro.md
    - Your first project: tutorial/first_project.md
    - Running hemlock locally: tutorial/run_local.md
    - Question polymorphs: tutorial/qpolymorphs.md
    - Data: tutorial/data.md
    - Validate: tutorial/validate.md
    - Submit: tutorial/submit.md
    - Compile: tutorial/compile.md
    - Navigate: tutorial/navigate.md
    - Page logic: tutorial/page_logic.md
    - Comprehension check: tutorial/comp_check.md
    - Random assignment: tutorial/random_ass.md
    - Proposer branch: tutorial/proposer_branch.md
    - Responder branch: tutorial/responder_branch.md
    - Debugging: tutorial/debug.md
    - Deployment: tutorial/deploy.md
    - Bells and whistles: tutorial/extra.md
  - Setup:
    - Windows: setup/win.md
    - Windows Subsystem for Linux: setup/wsl.md
    - Mac: setup/mac.md
    - Linux: setup/linux.md
  - Application: 
    - Setting and initialization: app.md
    - Debugging: debug.md
  - Functions:
    - Compile: functions/compile.md
    - Debug: functions/debug.md
    - Submit: functions/submit.md
    - Validate: functions/validate.md
  - Models:
    - Bases: models/bases.md
    - Branch: models/branch.md
    - Embedded data and timers: models/embedded.md
    - Function models: models/functions.md
    - Page: models/page.md
    - Participant: models/participant.md
    - Question: models/question.md
    - Worker: models/worker.md
  - Question polymorphs:
    - Bases: questions/bases.md
    - Blank: questions/blank.md
    - Check: questions/check.md
    - Choice: questions/choice.md
    - Dashboard: questions/dashboard.md
    - Download: questions/download.md
    - File upload: questions/file.md
    - Input: questions/input.md
    - Label: questions/label.md
    - Range: questions/range.md
    - Select: questions/select.md
    - Textarea: questions/textarea.md
  - Tools:
    - Comprehension check: tools/comprehension.md
    - Language: tools/lang.md
    - MTurk: tools/mturk.md
    - Navbar: tools/navbar.md
    - Randomization: tools/random.md
    - Statics: tools/statics.md
    - Titrate: tools/titrate.md
    - Utilities: tools/utils.md
  - Security: security.md
  - Changelog: changelog.md
  - Acknowledgements: acknowledgements.md
theme: readthedocs
extra_css:
  - css/extra.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
  - admonition
  - footnotes
  - mdx_math
  - pymdownx.details
  - pymdownx.superfences