BUCKET: hemlock-bucket2357
CHROMEDRIVER_PATH: /app/.chromedriver/bin/chromedriver
CURRENT_ENV: local
GOOGLE_APPLICATION_CREDENTIALS: env/gcp-credentials.json
GOOGLE_CHROME_BIN: /app/.apt/usr/bin/google_chrome
POSTGRES_PRODUCTION_PLAN: standard-0
PROCTYPE_PRODUCTION: standard-1x
REDIS_PRODUCTION_PLAN: premium-1
WEB_PRODUCTION_SCALE: '3'
WORKER: 'False'
WORKER_PRODUCTION_SCALE: '3'
