<<<<<<< HEAD
BUCKET: hemlock-bucket-j75ltxpe4e
=======
BUCKET: hemlock-bucket-nwiwjz3py2
>>>>>>> d047ff113e7a9f9be0ed7b8732600f6ef428b6b2
CHROMEDRIVER_PATH: /app/.chromedriver/bin/chromedriver
GOOGLE_APPLICATION_CREDENTIALS: env/gcp-credentials.json
URL_ROOT: http://hlk-test235.herokuapp.com
