BUCKET: hemlock-bucket2357
CHROMEDRIVER_PATH: /app/.chromedriver/bin/chromedriver
CURRENT_ENV: production-lite
GOOGLE_APPLICATION_CREDENTIALS: env/gcp-credentials.json
GOOGLE_CHROME_BIN: /app/.apt/usr/bin/google_chrome
WKHTMLTOIMAGE: /app/bin/wkhtmltoimage
WKHTMLTOPDF_BUILDPACK_URL: https://github.com/dsbowen/heroku-buildpack-wkhtmltopdf
WORKER: '0'
