BUCKET: hemlock-bucket2357
CURRENT_ENV: local
GOOGLE_APPLICATION_CREDENTIALS: env/gcp-credentials.json
WKHTMLTOIMAGE: /app/bin/wkhtmltoimage
WKHTMLTOPDF_BUILDPACK_URL: https://github.com/dsbowen/heroku-buildpack-wkhtmltopdf
WORKER: '0'
